
import { Dictionaries } from './types';

export const DICT: Dictionaries = {
  ja: {
    nav_about: "About",
    nav_service: "Service",
    nav_contact: "Contact",
    service_title: "Services",
    items: "items",
    vision_body: "MILZTECHは、“感性×テクノロジー”を軸にした次世代型クリエイティブ・テックカンパニーです。フォトグラファーとして培った観察力、構成力、表現力、それらをAI、データ、指示、そしてデザインに融合させ、人や企業、そして世界をつなぐ新しい「体験のプラットフォーム」を創造します。",
    core_title: "From Creative Eyes\nTo Intelligent Systems.",
    core_body: "",
    svc_ai_desc: "AIと既存テクノロジーを融合させ, 問題解決を行なっています。",
    svc_ai_project_estate: "EstateCopy AI",
    svc_ai_detail_estate: "*不動産業者様向けの文章自動制作サポート",
    svc_ai_project_openframe: "Openframe",
    svc_ai_detail_openframe: "*自動マッチングや画像編集＋納品システムを構築し業務効率化を実現。",
    svc_pv_desc: "写真・動画の撮影および編集サービスを行なっております。",
    svc_pv_project: "Stagingpro",
    svc_pv_detail: "*弊社運営のVirtual Stagingをはじめとした、画像・動画編集を提供しているプラットフォーム。",
    svc_travel: "Coming Soon",
    project_example_label: "プロジェクト例",
    contact_title: "Contact",
    contact_body: "プロジェクトの構想、あるいは共創への誘いをお聞かせください。",
    contact_cta: "Establish Contact",
    founders_label: "Meet the Founders",
    founder_wada_role: "Chairman",
    founder_takano_role: "CCIO (Chief Creative & Innovation Officer)",
    founders_message: "私たちの使命は、「１つでも多くの光（アイデア）を輝かせる（現実化）」こと。テクノロジーを“冷たいもの”ではなく、人の感情やストーリーを加速させる“温かい力”として使う。それが、フォトグラファー出身の私たちにしかできない、MILZTECHの在り方です。",
    form_name: "Name",
    form_email: "Email Address",
    form_message: "Message",
    form_send: "Transmit Message",
    form_sending: "Processing...",
    form_success: "Transmission Complete.",
    form_ai_reply_label: "AI Auto-Response",
    // Company Outline
    company_title: "Outline",
    co_name_label: "会社名",
    co_name_value: "マイルズテック株式会社",
    co_est_label: "設立",
    co_est_value: "2025年11月",
    co_address_label: "所在地",
    co_address_value: "〒156-0054 東京都世田谷区桜ヶ丘5-20-10-102",
    co_business_label: "事業内容",
    co_business_value: "写真撮影・動画撮影・写真編集・映像編集 / AI開発",
  },
  en: {
    nav_about: "About",
    nav_service: "Service",
    nav_contact: "Contact",
    service_title: "Services",
    items: "items",
    vision_body: "MILZTECH is a next-generation creative-tech company centered on 'Sensitivity × Technology'. We fuse the observation, composition, and expression cultivated as a photographer with AI, data, and design to create a new 'Experience Platform' that connects people, businesses, and the world.",
    core_title: "From Creative Eyes\nTo Intelligent Systems.",
    core_body: "",
    svc_ai_desc: "We provide problem-solving by merging AI with existing technologies.",
    svc_ai_project_estate: "EstateCopy AI",
    svc_ai_detail_estate: "*Automated text generation support for real estate agents.",
    svc_ai_project_openframe: "Openframe",
    svc_ai_detail_openframe: "*Building automated matching and image editing/delivery systems for operational efficiency.",
    svc_pv_desc: "We provide photography and video shooting/editing services.",
    svc_pv_project: "Stagingpro",
    svc_pv_detail: "*An image/video editing platform including our proprietary Virtual Staging service.",
    svc_travel: "Coming Soon",
    project_example_label: "Project Example",
    contact_title: "Contact",
    contact_body: "Tell us about your vision or invitation for co-creation.",
    contact_cta: "Establish Contact",
    founders_label: "Meet the Founders",
    founder_wada_role: "Chairman",
    founder_takano_role: "CCIO (Chief Creative & Innovation Officer)",
    founders_message: "Our mission is to make as many 'lights' (ideas) shine as possible. We use technology not as something 'cold,' but as a 'warm force' that accelerates human emotions and stories. That is the essence of MILZTECH—something only we, born with a photographer's eye, can achieve.",
    form_name: "Name",
    form_email: "Email Address",
    form_message: "Message",
    form_send: "Transmit Message",
    form_sending: "Processing...",
    form_success: "Transmission Complete.",
    form_ai_reply_label: "AI Auto-Response",
    // Company Outline
    company_title: "Outline",
    co_name_label: "Company Name",
    co_name_value: "MILZTECH Inc.",
    co_est_label: "Established",
    co_est_value: "November 2025",
    co_address_label: "Headquarters",
    co_address_value: "5-20-10-102 Sakuragaoka, Setagaya-ku, Tokyo 156-0054",
    co_business_label: "Business Activities",
    co_business_value: "Photography, Videography, Image/Video Editing, AI Development",
  }
};

export const SERVICE_ITEMS = ["AI Solution", "Production", "Experience"] as const;
